export const SUPPORTED_LANGUAGES = [
    { code: "en", name: "English", nativeName: "English" },
    { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
    { code: "te", name: "Telugu", nativeName: "తెలుగు" },
    { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
    { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
    { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
    { code: "mr", name: "Marathi", nativeName: "मराठी" },
    { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
    { code: "bn", name: "Bengali", nativeName: "বাংলা" },
    { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
    { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ" },
    { code: "as", name: "Assamese", nativeName: "অসমীয়া" },
    { code: "ur", name: "Urdu", nativeName: "اردو" },
    { code: "kok", name: "Konkani", nativeName: "कोंकणी" },
    { code: "sa", name: "Sanskrit", nativeName: "संस्कृतम्" },
    { code: "mni", name: "Manipuri (Meitei)", nativeName: "মৈতৈলোন্" },
    { code: "brx", name: "Bodo", nativeName: "बर'" },
    { code: "doi", name: "Dogri", nativeName: "डोगरी" },
    { code: "ks", name: "Kashmiri", nativeName: "کأشُر" },
    { code: "mai", name: "Maithili", nativeName: "मैथिली" },
    { code: "ne", name: "Nepali", nativeName: "नेपाली" },
    { code: "sat", name: "Santali", nativeName: "ᱥᱟᱱᱛᱟᱲᱤ" },
    { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
];
