"""create form links

Revision ID: ac61d384b958
Revises: c3b9f1a2d4e6
Create Date: 2026-07-12 17:03:28.674067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac61d384b958'
down_revision: Union[str, Sequence[str], None] = 'c3b9f1a2d4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('form_version_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_form_links_id'), 'form_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_links_id'), table_name='form_links')
    op.drop_table('form_links')
    # ### end Alembic commands ###
